import '../globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import logo from '@/assets/images/logo.png'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function MainLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="bg-white py-4">
					<div className="container">
						<Image alt="logo" src={logo} height={34} width={34} />
					</div>
				</header>
				<main className="container">
					<div>{children}</div>
				</main>
			</body>
		</html>
	)
}
