import dynamic from 'next/dynamic'

import Header from '@/components/common/mainLayout/header/Header'
import Sidebar from '@/components/common/mainLayout/sidebar/Sidebar'

const DynamicCheckUser = dynamic(() => import('@/providers/auth/CheckUser'), {
	ssr: false,
})
// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// }
export default function MainLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<DynamicCheckUser>
			<div className="pt-[90px]">
				<Header />
				<main className="container flex">
					<Sidebar />
					<div className="flex-grow">{children}</div>
				</main>
			</div>
		</DynamicCheckUser>
	)
}
