import Image from 'next/image'

import Header from '@/components/common/mainLayout/header/Header'
import Sidebar from '@/components/common/mainLayout/sidebar/Sidebar'

import CheckUser from '@/providers/auth/CheckUser'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function MainLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<CheckUser>
			<Header />
			<main className="container flex">
				<Sidebar />
				<div>{children}</div>
			</main>
		</CheckUser>
	)
}
